config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :posts
  

  root to: 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	# validates presence
	validates :title, :content, :author, :category, presence: true
	validates :title, uniqueness: true

	# # validates numericality
	# validates :category, numericality: true, if: :method_name_that_should_return_true
	# # regex
	# validates :category, format: /@/
	# 			:field, :typeOfValidation {options}
	# validates :category, presence: true,
	# 					 inclusion: {in: ['news', 'fun']}

	# to check:
	# entry.valid? (t/f) or entry.errors to check errors, entry.errors[:title]

	# def to_s
	# 	self.title
	# end
	
	def lead
		self.content.to_s.first(100) + '...'
	end

	def duplicated(other_post)
		if self.title == other_post.title
			"Duplicated"
		end
	end
	# or

	# def ==(other)
	# 	self.title == other.title	
	# end

	def by?(check_author)
		if self.author == check_author.to_s
			return true
		end
	end

	def same_category?(other_post)
		if self.category == other_post.category
			return true
		else
			return false
		end
	end


	def self.entitled(value)
		# lower(field)
		where("lower(title) LIKE ? or lower(content) LIKE ?", "%#{value.downcase}%", "%#{value.downcase}%")

		# SELECT * FROM posts
		# WHERE lower(title) LIKE '%awesome%'
		# % -> any number of characters before/after
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :email, presence: true, uniqueness: true
	validates :date_of_birth, presence: true
	# different method
	validate :at_least_18
	validate :em_belongs_to

	def at_least_18
		if date_of_birth > 18.years.ago
			errors.add(:date_of_birth, "Must be at least 18 years old")
		end
	end

	def em_belongs_to
		# if !email.ends_with?("ryanbrunner.ca")
		# 	errors.add(:email, "Your e-mail must belong to ryanbrunner.ca domain")
		# end
		if not email.ends_with?("ryanbrunner.ca")
			errors.add(:email, "Your e-mail must belong to ryanbrunner.ca domain")
		end

		# unless email.ends_with?("ryanbrunner.ca")
		# 	errors.add(:email, "Your e-mail must belong to ryanbrunner.ca domain")
		# end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  # needed to add form tag
  protect_from_forgery with: :exception

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    if params[:query].present?
      @posts = Post.entitled(params[:query])
    else
      @posts = Post.all
    end
  end

  def show
  	@post = Post.find(params[:id])
  end

  def new
  	@post = Post.new
  end

  def create
    
    # if Post.valid?
    #   Post.create({
    #     title: params[:post][:title],
    #     content: params[:post][:content],
    #     author: params[:post][:author],
    #     category: params[:post][:category]
    #   })

    #   redirect_to root_path
    # else
    #   error_message = @post.errors.messages
    #   render error_message
    # end

  	Post.create({
  		title: params[:post][:title],
  		content: params[:post][:content],
  		author: params[:post][:author],
  		category: params[:post][:category]
  	})

  	# redirect_to root_path
  	# render text: params
  end

  # /posts/:id -> params[:id]
  def edit
    @post = Post.find(params[:id])

  end
  def post_params
    params.require(:post).permit(:title, :author, :content, :category)
  end
  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to root_path

    # if @post.valid?
    #   @post.update(post_params)
    #   redirect_to root_path
    # else
    #   error_message = @post.errors.messages
    #   render error_message
    # end
    
  end

  # def search
  #   @posts = Post.entitled(params[:query])
  #   # render the view index (above), but only render the posts filtered
  #   render :index
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :date_of_birth)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h2>Search here:</h2>
<%= form_tag root_path, method: 'GET' do %>
	<input type="search" name="query" placeholder="Search posts here">
	<input type="submit" value="SEARCH NOW">
<% end %>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h2>Edit this post!</h2>

<%= form_for @post do |f|%>
	<%= f.label :title %>
	<%= f.text_field :title, :placeholder => "Title" %>
	<%= f.label :content %>
	<%= f.text_area :content, :placeholder => "Content" %>
	<%= f.label :author %>
	<%= f.text_field :author , :placeholder => "Author"%>
	<%= f.label :category %>
	<%= f.text_field :category, :placeholder => "Category" %>
	<%= f.submit :submit %>
<% end %>

<%= link_to "Cancel", root_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>
<p>Find me in app/views/posts/index.html.erb</p>
<ul>
	<% @posts.each do |post| %>
	<li>
		<!-- <h2><a href="<%= post_path(post) %>"> <%= post.title %></a></h2> -->
		<!-- <h2><%= link_to post.title, post_path(post) %></h2> -->
		<h2><%= link_to post.title, post %></h2>
		<p>By <%= post.author %> on <%= post.created_at %></p>
		<p><%= post.content %></p>
		<%= link_to "Edit me", edit_post_path(post) %>

	</li>
	<% end %>
</ul>

<%= link_to "Add post", new_post_path %>

<%= link_to "Add User", new_user_path %>

app/views/posts/new.html.erb
<h2>Create a new post here!</h2>
<!-- form_tag '/posts', method: "POST" do -->
<!-- f is being yielded to the block -->
<%= form_for @post do |f|%>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.label :content %>
	<%= f.text_area :content %>
	<%= f.label :author %>
	<%= f.text_field :author %>
	<%= f.label :category %>
	<%= f.text_field :category %>
	<%= f.submit :submit %>
<% end %>

<%= link_to "Back to list", root_path %>

<!-- make signup on hacklaunch like this -->

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.content %></p>

<%= link_to "Back to list", root_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br>
    <%= f.date_select :date_of_birth %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Date of birth</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.date_of_birth %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @user.date_of_birth %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>